#!/bin/bash
set -eu

if [ -z "${MYSQL_REPLICATION_PASSWORD:-}" ]; then
  echo "MYSQL_REPLICATION_PASSWORD is required for primary replication setup" >&2
  exit 1
fi

APP_WRITE_USER="${MYSQL_WRITE_USER:-${MYSQL_USER:-}}"
APP_WRITE_PASSWORD="${MYSQL_WRITE_PASSWORD:-${MYSQL_PASSWORD:-}}"
APP_READ_USER="${MYSQL_READ_USER:-${MYSQL_USER:-}}"
APP_READ_PASSWORD="${MYSQL_READ_PASSWORD:-${MYSQL_PASSWORD:-}}"

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE USER IF NOT EXISTS '${APP_WRITE_USER}'@'%' IDENTIFIED BY '${APP_WRITE_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES ON \`${MYSQL_DATABASE}\`.* TO '${APP_WRITE_USER}'@'%';
CREATE USER IF NOT EXISTS '${APP_READ_USER}'@'%' IDENTIFIED BY '${APP_READ_PASSWORD}';
GRANT SELECT ON \`${MYSQL_DATABASE}\`.* TO '${APP_READ_USER}'@'%';
CREATE USER IF NOT EXISTS '${MYSQL_REPLICATION_USER:-replica}'@'%' IDENTIFIED BY '${MYSQL_REPLICATION_PASSWORD}';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO '${MYSQL_REPLICATION_USER:-replica}'@'%';
SQL

if [ -n "${MYSQL_REPLICA_STATUS_USER:-}" ] && [ -n "${MYSQL_REPLICA_STATUS_PASSWORD:-}" ]; then
  mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE USER IF NOT EXISTS '${MYSQL_REPLICA_STATUS_USER}'@'%' IDENTIFIED BY '${MYSQL_REPLICA_STATUS_PASSWORD}';
GRANT REPLICATION CLIENT ON *.* TO '${MYSQL_REPLICA_STATUS_USER}'@'%';
FLUSH PRIVILEGES;
SQL
else
  mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
FLUSH PRIVILEGES;
SQL
  echo "MYSQL_REPLICA_STATUS_USER/PASSWORD not set; replica status account was not created" >&2
fi
