FROM mysql:8.0

COPY conf/replica.cnf /etc/mysql/conf.d/replica.cnf
COPY init/replica/ /docker-entrypoint-initdb.d/

RUN chmod 644 /etc/mysql/conf.d/replica.cnf \
    && find /docker-entrypoint-initdb.d -type f -name "*.sh" -exec chmod 755 {} \; \
    && find /docker-entrypoint-initdb.d -type f -name "*.sql" -exec chmod 644 {} \;
